### ISSUE TITLE
wave

### ISSUE THREAD

**Issue by Kezarus-tech** [Alphish/gm-community-toolbox#97] opened 2024-11-29 12:37 UTC
Great and simple function to returns a value that will wave back and forth between [from-to] over [duration] seconds.

```
/// @description wave( from, to, duration, offset )
/// @param  from
/// @param  to
/// @param  duration
/// @param  offset 
function wave(argument0, argument1, argument2, argument3) {
	/// CREDIT TO: Sara Spalding
 
	var a4 = (argument1 - argument0) * 0.5;
	return argument0 + a4 + sin((((current_time * 0.001) + argument2 * argument3) / argument2) * (pi*2)) * a4;
}
```

**Comment by Alphish** [comment] 2024-11-29 14:21
Duplicate of #21, so closing this one here.

But also, I don't mind reviving the discussion there! Just wondering about a name that might be more unmistakable and also doesn't reserve a variable name for tower defense games waves or something... 🤔

**Closed** 2024-11-29 14:21 UTC
Labels: feature ✨
