### ISSUE TITLE
draw_arc

### ISSUE THREAD

**Issue by Mercerenies** [Alphish/gm-community-toolbox#5] opened 2023-06-14 19:52 UTC
`draw_arc` behaves like `draw_circle` but only draws part of the outline of the circle, from a given starting angle to ending angle.

```
function draw_arc(xx, yy, radius, start_angle, end_angle) {
  draw_primitive_begin(pr_trianglefan);
  draw_vertex(xx, yy);

  for (var i = 0; i < 50; i++) {
    var theta = lerp(start_angle, end_angle, i / 50);
    draw_vertex(xx + radius * dcos(theta), yy - radius * dsin(theta));
  }

  draw_primitive_end();
}
```

Possible point of expansion: Supporting a "filled" version as well, which draws either a pie slice or a [segment](https://en.wikipedia.org/wiki/Circular_segment) rather than just the outline.

**Comment by Alphish** [comment] 2023-06-14 21:18
Note sure about this one, as there might be varying arc-drawing needs? Like, someone would want their arc to have smaller or greater precisions, yet another person would want to draw their arc with varying thickness, yet another would use shaders to draw their arcs...
It feels like one of those functions that under its innocent-sounding name hides tons of design decisions that some potential package users would find too disagreeable.

**Comment by MagnusMagnusson** [comment] 2023-06-16 10:45
Precision and width could be function parameters, or members of the more advanced "draw_arc_ext". Doesn't help people who want to draw things with shaders, but it's a step towards a solution.

**Comment by Alphish** [comment] 2023-08-24 17:17
I'm going to leave this one up for discussion, some more research is needed about how people handle their arc-drawing needs. Not saying "no", but with different valid ways to handle it - not just at the implementation level, but at the expected behaviour as well - it might be wise to explore how different people approach arc-drawing before reserving `draw_arc` name.

Note: It might become less of a concern once Prefabs arrive and the user will be able to override Prefab functions with same named project-specific counterpart. If that will be the case, I won't object to adding some well-liked `draw_arc` implementation then. ^^

**Comment by gnysek** [comment] 2023-08-24 18:11
My proposal would be, that for precision we could use default GM value. However I just found out, that there's no way to read it back, so I've made a feature request in advance: https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1279

**Comment by gnysek** [comment] 2023-08-24 18:14
btw. on GMLscripts.com there are functions for:
`draw_arc`, `draw_chord`, `draw_curve` and `draw_pie` - pie and curve looks like they also could be added, especially that it seems they were part of GM5 (however I don't remember that).

**Comment by Alphish** [comment] 2023-08-30 08:44
Good point about covering different functions - we might actually want to look into which of these functions we want covered.
I'll return to this feature request after the GMC Jam; FrostyCat suggested adding `precision` as the last parameter, that could later be replaced with the circle precision getter, and this might be the way to go.

**Comment by gnysek** [comment] 2023-08-30 12:52
Yes, setting precision as last param is a good idea, as it's easy to either remove it, or replace with `foo(value = gm_function_name())` as GM allows such things from what I see, so it could be still overridden on demand and backward compatible, when getting current precision would became available.

**Comment by Alphish** [comment] 2024-08-19 13:32
I think the version of `draw_arc` from GMLscripts.com is worth looking into. If I understand correctly, it applies the precision to the ellipse as a whole and then cuts an arc out of it, as opposed to adding the number of segments equal to the precision, which means effectively more detail for low angles and less detail for high angles? This kind of behaviour is worth replicating, so that refardless of the angles combination same sub-arcs will be drawn consistently.

Also, I think `draw_pie` and `draw_chord` might as well be added alongside `draw_arc`, since they need to calculate basically the same curve (maybe they could in fact share some static function for populating vertices along the arc). `draw_curve` seems to be in a different function category altogether, so I'd rather not include it in this FR.

I'd still like to keep the `draw_arc` function signature as presented by Mercerenies. Going by center, radius and starting/ending angle seem like a whole lot more convenient way to handle it than defining ellipse bounding box than starting/ending points. So I'm thinking of signatures like:
- `draw_arc(x, y, radius, anglefrom, angleto, precision = 24)` (24 is the default precision, so I'd use this until we get `draw_get_precision()` sort of function)
- `draw_pie(x, y, radius, anglefrom, angleto, outline = false, precision = 24)`
- `draw_chord(x, y, radius, anglefrom, angleto, outline = false, precision = 24)`

I'd like the implementation to match the precision of the whole circle (e.g. given precision of 24, it would draw 4 segments' worth for 60 degrees angle difference, as opposed to 24 regardless of the angle), like what _I think_ is done in the GMLscripts.com  `draw_arc` and similar functions implementations. It's more technically difficult, but it should make sub-arc segments appearance consistent regardless of how broad or how narrow the angle will end up.

Is everyone on board of that? If that's alright, I might try and draft some implementation, or someone else can provide one.

Once we have the signatures and the precision handling settled, I think it'll be ready for name voting and eventual addition to the toolbox.

**Comment by gnysek** [comment] 2024-08-19 13:50
I'm not sure if we could use GM `draw_get_circle_precision()` when it would became available, as seems that this function under the hood is used for kinda interesting caching of `sin` and `cos` values for each of "steps" in circle ( https://github.com/YoYoGames/GameMaker-HTML5//develop/scripts/yyWebGL.js#L316 ).
Drawing for toolbox functions would be done between `anglefrom, angleto` arguments, so it need to be decided what `precision` will be - number of segments in circle (so it would cover ideally over GM circles), number of segments between those angles, or something between (like calculating how many degrees segments have, so in edge case like 1 degree, we won't draw 24 lines) -  complexity of calculations in all those cases are drastically different.

**Comment by Alphish** [comment] 2024-08-19 14:02
I imagine the arc would be a cut-out of a base circle.

So e.g. if the precision is 24 - with each segment spanning 15 degrees worth - then given angles from 5deg to 128deg it would draw:
- part of 0-15 segment matching the 5-15 angle range
- segments 15-30, 30-45, 45-60, 60-75, 75-90, 90-105, 105-120
- part of 120-135 segment matching the 120-128 angle range

Here is a little graphic showing the general idea, with the green angle range "clipping" to an arc what would otherwise be the 8-precise circle:

![image](https://github.com/user-attachments/assets/e8a948dd-31c7-4a10-ba7c-59acfd0a4bfa)

The most annoying part would be calculating segments intersections for the initial and ending segments, the rest should be pretty straightforward I think.

**Comment by gnysek** [comment] 2024-08-19 15:01
A picture is worth a thousand words - it perfectly describes what approach will be used, and in that case for sure it could benefit from `draw_get_circle_precision()`.

**Comment by Alphish** [comment] 2024-11-23 13:48
Implemented and merged!

After some discussions here and there I settled on the naming of:
- `draw_arc`
- `draw_circle_sector`
- `draw_circle_segment`
- `draw_ring` (for drawing an area between two radii)
- `draw_ring_arc` (for drawing a slice of that area
Hopefully it'll be clear what each function does, and if not, that it will at least be easy to learn (e.g. circle sector and segments can be looked up on Wikipedia).

**Closed by Alphish** 2024-11-23 13:48 UTC
Labels: feature ✨, accepted 🚀
